// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxjoaghopyrnnrsrmapu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4am9hZ2hvcHlybm5yc3JtYXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDEzMTQsImV4cCI6MjA2ODM3NzMxNH0.5ZGW5rVR0B5Y8wbFt5UT7Nd990PIQwH9z-C4NunGtAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});